Fix sync repos to actually work, and make more useful.

diff --git a/bin/sync-repos b/bin/sync-repos
--- a/bin/sync-repos
+++ b/bin/sync-repos
@@ -1,17 +1,29 @@
 #!/usr/bin/env zsh
 
-pushd
 cd $ZDOTDIR/remote
 for i in $(find . -maxdepth 1 -regex '.*[^root]'); do
-	if [ ! "$i" = "." ] && \
-		[ -d "$i/etc" ]; then
-		cd "$i/etc"
-		date >> ~/.gitsynclog
-		echo $i >> ~/.gitsynclog
-		if ! git pull "$ZDOTDIR/etc" master >> ~/.gitsynclog 2>&1; then
-			    echo "Error syncing git. See ~/.gitsynclog."
-		fi
-		echo >> ~/.gitsynclog
+	if [ ! "$i" = "." ]; then
+			date >> ~/.gitsynclog
+			echo $i >> ~/.gitsynclog
+
+			(if [ ! -d "$i/etc" ]; then
+			    echo "Detected new remote host: $i"
+					cd "$i"
+					git clone "$ZDOTDIR/etc"
+					cd etc
+					git submodule init
+					git submodule update
+					remote_home=$(echo "$i" | sed 's/\.\///') # strip leading ./
+					HOME="$ZDOTDIR/remote/$remote_home" shell/setup_symlinks
+					echo "Done setting up new remote host: $i"
+			fi)  >> ~/.gitsynclog 2>&1
+
+			(if 	[ -d "$i/etc" ]; then
+					cd "$i/etc"
+					if ! git pull "$ZDOTDIR/etc" master; then
+							echo "Error syncing git. See ~/.gitsynclog."
+					fi
+					echo
+			fi) >> ~/.gitsynclog 2>&1
 	fi &
 done
-popd
