Fix sshmount.

diff --git a/shell/prefs b/shell/prefs
--- a/shell/prefs
+++ b/shell/prefs
@@ -128,19 +128,27 @@ sshmount() {
     # create mount point
     mkdir -p "$remote_path"
 
-    # make future instances passwordless
-    ssh-add &> /dev/null # idempotent, registers key
-    cat $ZDOTDIR/.ssh/id_rsa.pub | ssh $LOGNAME@$1 'cat - >> .ssh/authorized_keys'
-
     # apparently these are best for performance
-    sshfs_opts="-o allow_other,reconnect,transform_symlinks,ssh_command=$ZDOTDIR/etc/bin/ssharcfour"
+    sshfs_opts="-oreconnect,transform_symlinks,ssh_command=$ZDOTDIR/etc/bin/ssharcfour"
+		#sshfs_opts="-o ssh_command=$ZDOTDIR/etc/bin/ssharcfour"
 
     # Remount
     fusermount -u "$remote_path" &> /dev/null
-    sshfs $LOGNAME@$1:/ "$remote_path" $sshfs_opts
+    if ! sshfs "$sshfs_opts" "$LOGNAME"@"$1":/ "$remote_path"; then
+				echo >&2 "sshfs failed!"
+				return 1
+		fi
 
     cd $ZDOTDIR/remote
     ln -Tsf "$1-root/home/$LOGNAME" "$1"
+
+    # make future instances passwordless
+    ssh-add &> /dev/null # idempotent, registers key
+		mkdir -p "$1-root/home/$LOGNAME/.ssh"
+		remote_key_file="$1-root/home/$LOGNAME/.ssh/authorized_keys"
+		if ! grep "$(cat $ZDOTDIR/.ssh/id_rsa.pub)" $remote_key_file &> /dev/null; then
+				cat $ZDOTDIR/.ssh/id_rsa.pub >> $remote_key_file
+		fi
 }
 
 if [ -d /j* ]; then
